pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS = credentials('docker_access')
        ANSIBLE_VPS_CREDENTIALS = credentials('client_vps_access')
    }
    stages {
        stage('Test Cloning Files') {
            steps {
                sh 'ls | grep music-reader'
                sh 'ls jenkins/music-distribution | grep Jenkinsfile'
            }
        }
        stage('Check and Install Tools (docker, docker-compose, mvn)') {
            steps {
                script {
                    def installDocker = {
                        echo "Docker is not installed. Installing..."
                        sh 'curl -fsSL https://get.docker.com -o get-docker.sh'
                        sh 'sh get-docker.sh'
                        def currentUserName = sh(script: 'whoami', returnStdout: true).trim()
                        sh "sudo usermod -aG docker ${currentUserName}"
                    }

                    def installDockerCompose = {
                        echo "Docker Compose is not installed. Installing..."
                        sh 'curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
                        sh 'chmod +x /usr/local/bin/docker-compose'
                    }


                    def installAnsible = {
                        echo "Ansible is not installed. Installing..."
                        sh 'apt update'
                        sh 'apt install ansible -y'
                        sh 'apt-get install sshpass'
                        sh 'ansible --version'
                    }

                    if (sh(script: 'docker --version', returnStatus: true) != 0) {
                        installDocker()
                    } else {
                        echo "Docker is already installed."
                    }

                    if (sh(script: 'docker-compose --version', returnStatus: true) != 0) {
                        installDockerCompose()
                    } else {
                        echo "Docker Compose is already installed."
                    }


                    if (sh(script: 'ansible --version', returnStatus: true) != 0) {
                        installAnsible()
                    } else {
                        echo "Ansible is already installed."
                    }
                }
            }
        }
        /*stage('Test Distribution project') {
            steps {
                sh 'cd music-reader && mvn test -Ptest'
            }
        }
        stage('Build Node Project') {
            steps {
                sh 'rm -R -f music-reader/target/dist/*'
                sh 'cd music-reader && mvn verify -Pprod'
                sh 'cp distribution/target/*.jar distribution/target/distribution-latest.jar'
                sh 'ls distribution/target/'
                sh 'ls ./'
            }
        }
        stage('Deploy on Docker Hub') {
            steps {
                sh 'docker build --tag feavfeav/music-reader-server:latest ./music-reader/'
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                sh 'docker push feavfeav/music-reader-server:latest'
            }
        }*/
        stage('Deploy on VPS with Ansible') {
            steps {
                script {
                    sh 'ansible-playbook --syntax-check -i ansible/hosts.yml ansible/music-reader/deploy.yml'
                    sh 'ansible -i ansible/music-reader/hosts.yml all -m ping   -e ansible_ssh_pass=$ANSIBLE_VPS_CREDENTIALS_PSW'
                    sh 'ansible-playbook -i ansible/music-reader/hosts.yml ansible/music-reader/deploy.yml  -e ansible_ssh_pass=$ANSIBLE_VPS_CREDENTIALS_PSW'
                }

            }
        }

    }
}
