version: '3'
services:
  # Service MySQL
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD:
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: music_distribution
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Service phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql-db

volumes:
  mysql-data: